=== josselynwebb/GPATS-Compare/Source/ISS/ISS Documentation/CICL_SDD/TestStationInstanceSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by tmcquillen (Access Research Corporation) -->
<xs:schema xmlns:c="http://www.ieee.org/ATML/2005/08/Common" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.1">
	<xs:import namespace="http://www.ieee.org/ATML/2005/08/Common" schemaLocation="Common.xsd"/>
	<xs:complexType name="InstrumentAddressType">
		<xs:all>
			<xs:element name="InstrumentQueryID" type="xs:string" minOccurs="0"/>
			<xs:element name="InstrumentTypeNumber" minOccurs="0"/>
			<xs:element name="ControllerType" minOccurs="0"/>
			<xs:element name="ControllerNumber" minOccurs="0"/>
			<xs:element name="PrimaryAddress" type="xs:string" minOccurs="0"/>
			<xs:element name="SecondaryAddress" type="xs:string" minOccurs="0"/>
			<xs:element name="SubModuleAddress" type="xs:string" minOccurs="0"/>
		</xs:all>
	</xs:complexType>
		<xs:simpleType name="ResourceUsage">
		<xs:annotation>
			<xs:documentation>Basic resource usage</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Power"/>
			<xs:enumeration value="Source"/>
			<xs:enumeration value="Sensor"/>
			<xs:enumeration value="Switch"/>
			<xs:enumeration value="Digital"/>
			<xs:enumeration value="Bus"/>
			<xs:enumeration value="I/O"/>
		</xs:restriction>
	</xs:simpleType>
<xs:element name="TestStationInstance">
		<xs:annotation>
			<xs:documentation>Document the attributes and asset configuration of an instance of a Test Station</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PublicAssets">
					<xs:annotation>
						<xs:documentation>Register a Instrument Assets</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Asset" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Instrument Specifics</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="InstrumentNumber" type="xs:int"/>
										<xs:element name="InstrumentName" type="xs:string"/>
										<xs:element name="InstrumentDriver" type="xs:string"/>
										<xs:element name="InstrumentAddress" type="InstrumentAddressType" minOccurs="0"/>
										<xs:element name="ResourceType" type="ResourceUsage" minOccurs="0"/>
										<xs:element name="SimulationLevel" type="xs:string" minOccurs="0"/>
										<xs:element name="DebugLevel" type="xs:string" minOccurs="0"/>
										<xs:sequence>
											<xs:element name="PhysicalResources" minOccurs="0">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="PhysicalResource" maxOccurs="unbounded">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="ResourceID">
																		<xs:annotation>
																			<xs:documentation>Match TestStation ResourceID</xs:documentation>
																		</xs:annotation>
																	</xs:element>
																	<xs:element name="ResourceName">
																		<xs:annotation>
																			<xs:documentation>Match TestStation ResourceName</xs:documentation>
																		</xs:annotation>
																	</xs:element>
																	<xs:choice minOccurs="0">
																		<xs:element name="ResourceAddress"/>
																		<xs:element name="InstrumentAddress" type="InstrumentAddressType"/>
																	</xs:choice>
																	<xs:element name="SimulationLevel" type="xs:string" minOccurs="0"/>
																	<xs:element name="DebugLevel" type="xs:string" minOccurs="0"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="VirtualResources" minOccurs="0">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="VirtualResource" maxOccurs="unbounded">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="ResourceID">
																		<xs:annotation>
																			<xs:documentation>Match TestStation ResourceID</xs:documentation>
																		</xs:annotation>
																	</xs:element>
																	<xs:element name="ResourceName">
																		<xs:annotation>
																			<xs:documentation>Match TestStation ResourceName</xs:documentation>
																		</xs:annotation>
																	</xs:element>
																	<xs:element name="PhysicalResourceUsed">
																		<xs:annotation>
																			<xs:documentation>Blank separated list of Physical ResourceNames Used</xs:documentation>
																		</xs:annotation>
																	</xs:element>
																	<xs:element name="SimulationLevel" type="xs:string" minOccurs="0"/>
																	<xs:element name="DebugLevel" type="xs:string" minOccurs="0"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="designator" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== josselynwebb/GPATS-Compare/Target/ROOTDrive/Program Files (x86)/ATS/ISS/config/Station_Configuration_Files/TETS_CONFIG_FILES/TestStationInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
	<TestStationInstance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestStationInstanceSchema.xsd"
	     designator="ATS#1">
		<PublicAssets>
		<!-- Restrictions for DBG version Case sensitive and no blanks in names e.g. "<Asset" --> 
		<!--The Master Reset Button removes in forward order of this file-->
		<!-- Sensors -->
			<Asset>
				<InstrumentNumber>1</InstrumentNumber>
				<InstrumentName>DSO_1</InstrumentName>
				<InstrumentDriver>AtXmlHPE1428A.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>E1428A</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>17</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>2</InstrumentNumber>
				<InstrumentName>CNTR_1</InstrumentName>
				<InstrumentDriver>AtXmlAgE1420B.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>AgE1420B</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>18</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>						
			<Asset>
				<InstrumentNumber>3</InstrumentNumber>
				<InstrumentName>DMM_1</InstrumentName>
				<InstrumentDriver>AtXmlRi4152A.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>Ri4112</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>44</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			</Asset>
				<Asset>
				<InstrumentNumber>4</InstrumentNumber>
				<InstrumentName>RF_MEASAN_1</InstrumentName>
				<InstrumentDriver>AtXmlRfModAnal_B8701.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>B8701</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>27</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>5</InstrumentNumber>
				<InstrumentName>RF_CNTR_1</InstrumentName>
				<InstrumentDriver>AtXmlRfCntr_TETS.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>RF_CNTR_1</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>25</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>6</InstrumentNumber>
				<InstrumentName>RF_PWR_1</InstrumentName>
				<InstrumentDriver>AtXmlRf_Pwr_HPE1416A.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>RF_PWR</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>VXI</ControllerType>
					<ControllerNumber>0</ControllerNumber>
					<PrimaryAddress>28</PrimaryAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>	
		<!-- Buses -->
			<Asset>
				<InstrumentNumber>11</InstrumentNumber>
				<InstrumentName>MIL1553_1</InstrumentName>
				<InstrumentDriver>AtXmlLE1553_5.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID></InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<!-- The ControllerType field contains the windows "friendly" name of the adapter found in Network Places properties -->
					<!-- This name may not contain any spaces! The windows name may need to be changed to meet this requirement -->
					<ControllerType></ControllerType>
					<ControllerNumber></ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>			
			</Asset>	
			<Asset>
				<InstrumentNumber>12</InstrumentNumber>
				<InstrumentName>ETHERNET_1</InstrumentName>
				<InstrumentDriver>AtXmlSBSGigabit.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SBSGigabit</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<!-- The ControllerType field contains the windows "friendly" name of the adapter found in Network Places properties -->
					<!-- This name may not contain any spaces! The windows name may need to be changed to meet this requirement -->
					<ControllerType>Gigabit1</ControllerType>
					<ControllerNumber></ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
				
			</Asset>	
			<Asset>
				<InstrumentNumber>13</InstrumentNumber>
				<InstrumentName>ETHERNET_2</InstrumentName>
				<InstrumentDriver>AtXmlSBSGigabit.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SBSGigabit</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<!-- The ControllerType field contains the windows "friendly" name of the adapter found in Network Places properties -->
					<!-- This name may not contain any spaces! The windows name may need to be changed to meet this requirement -->
					<ControllerType>Gigabit2</ControllerType>
					<ControllerNumber></ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>8</InstrumentNumber>
				<InstrumentName>COM_1</InstrumentName>
				<InstrumentDriver>AtXmlSLSerial.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>COM</ControllerType>
					<ControllerNumber>1</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>9</InstrumentNumber>
				<InstrumentName>COM_2</InstrumentName>
				<InstrumentDriver>AtXmlSLSerial.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>COM</ControllerType>
					<ControllerNumber>2</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>15</InstrumentNumber>
				<InstrumentName>COM_3</InstrumentName>
				<InstrumentDriver>AtXmlSLSerial.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>COM</ControllerType>
					<ControllerNumber>3</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>16</InstrumentNumber>
				<InstrumentName>COM_4</InstrumentName>
				<InstrumentDriver>AtXmlSLSerial.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>COM</ControllerType>
					<ControllerNumber>4</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>17</InstrumentNumber>
				<InstrumentName>COM_5</InstrumentName>
				<InstrumentDriver>AtXmlSLSerial.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>COM</ControllerType>
					<ControllerNumber>5</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
			</Asset>
			<Asset>
				<InstrumentNumber>18</InstrumentNumber>
				<InstrumentName>CAN_1</InstrumentName>
				<InstrumentDriver>AtXmlCAN.dll</InstrumentDriver>
				<InstrumentAddress>
					<InstrumentQueryID>SLS7404</InstrumentQueryID>
					<InstrumentTypeNumber>1</InstrumentTypeNumber>
					<ControllerType>CAN</ControllerType>
					<ControllerNumber>1</ControllerNumber>
					<PrimaryAddress></PrimaryAddress>
					<SecondaryAddress></SecondaryAddress>
					<SubModuleAddress></SubModuleAddress>
				</InstrumentAddress>
				<SimulationLevel>0</SimulationLevel>
				<DebugLevel>0</DebugLevel>
				</PhysicalResources>
			</Asset>		
		<!-- Sources -->
			<Asset>
				<InstrumentNumber>20</InstrumentNumber>
				<InstrumentName>ARB_GEN_1</InstrumentName>
				<InstrumentDriver>AtXmlArb_AgE1445A.dll</InstrumentDriver>
